language: python
sudo: false
python:
    - "2.7"
    - "3.4"

services:
  - cassandra
  - elasticsearch

cache:
  directories:
    - $HOME/wheelhouse

env:
  - WHEELHOUSE=$HOME/wheelhouse

install:
  - travis_retry pip install invoke coveralls
  - travis_retry invoke wheelhouse --develop
  - travis_retry invoke requirements --develop
  - cp scrapi/settings/travis-dist.py scrapi/settings/local.py

before_script:
  - flake8 .

script:
  - invoke provider_map
  - invoke test

after_success:
  coveralls

notifications:
  flowdock: df4d2322a6b6ec2c086c8b6b22f4abed
